# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request for master branch
  push:
    branches: [ test-ci-naming ]
  pull_request:
    branches: [ test-ci-naming ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: 'Install OS Packages'
        run: |
          sudo apt update
          sudo apt --fix-broken install -y
          sudo apt install python3-pip -y
          pip3 install setuptools
          pip3 install pylint coverage
        

      - name: 'Install Docker'
        run: |
          sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
          sudo apt update
          sudo apt install docker-ce -y
          sudo systemctl status docker
          sudo usermod -a -G docker ${USER}
          docker info
        

      - name: Start kind
        run: bash -f ./azurepipeline/start.sh
        continue-on-error: true

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build project
        run: go build -v ./cmd/aks-periscope/aks-periscope.go

      - name: Run integration test
        run: go test -v -mod=mod ./tests/aksperiscopeintegration_test.go

      - name: Stop kind
        run: bash -f ./azurepipeline/stop.sh
        continue-on-error: true